// <auto-generated />
using KreatorQuizu.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KreatorQuizu.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20240522204851_Initial2")]
    partial class Initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("KreatorQuizu.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer_A")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer_B")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer_C")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer_D")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_q")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("KreatorQuizu.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quizes");
                });
#pragma warning restore 612, 618
        }
    }
}
